#!/bin/bash


logo=~/bin/bash/cobertura.gif
title="Cobertura"

screen -t cobertura bash -c "mvn clean test cobertura:cobertura && notify-send '$title' 'Done' -i $logo || (notify-send '$title' 'KO' -i $logo; read)"

