#!/usr/bin/env -S bash -e

function lastArgument {
	local args=$*
	if [ $# -gt 0 ]
	then
		argCount=$(($# - 1 ))
		shift $argCount
		echo $1
	else
		return 1
	fi
}

args=$*
directory=$(lastArgument $* || echo ".")

git init $args
cd $directory
git commit -m "First empty commit" --allow-empty
git branch base
git branch --set-upstream master base

cd - >/dev/null

