#!/bin/bash

# Deliver script :
#   create or use a tag
#   prepare shortlog for content anouncement
#   remind for pull instructions (external text file can be included)
#   send mail to recipients (list or file containing mails)
#     receiver can be direct or hidden (if a lot of people)
#   prepare an archive (tar.gz or zip) and push this to external server


