#!/usr/bin/env bash

RM_OPTIONS=$*

ls_others() {
  git ls-files -o --exclude-standard
}

files=$(ls_others)
if [[ $(echo "$files" | wc -w ) -gt 0 ]]; then
  ls_others | xargs -d "\n" rm "$RM_OPTIONS"
fi
