#!/usr/bin/env bash

set -e

icon="$HOME/Pictures/icon.png"
tmpdir=$XDG_RUNTIME_DIR
tmpbg=$(mktemp "$tmpdir/screen-XXX.png")

# override icon if passed as first shell argument
(( $# )) && { icon=$1; }

scrot -o "$tmpbg"

convert "$tmpbg" -scale 20% -scale 500% "$tmpbg"
if [ -r "$icon" ]
then
  convert "$tmpbg" "$icon" -gravity center -composite -matte "$tmpbg"
fi
i3lock -i "$tmpbg"
