#!/bin/bash

#==============================================================================
# The MIT License
#
# Copyright (c) 2010-, Frédéric Menou
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#==============================================================================

echo $(date +"%Y-%m-%d %H:%M:%S")
cd "$2" > /dev/null
result=$(git svn fetch --parent | tee -a /dev/stdout | wc -l)
if [ $result -gt 0 ]; then
	forward=$(git log --oneline remotes/trunk..master | wc -l)
	target=$(git svn find-rev remotes/trunk)
	if [ $forward -gt 0 ]; then
		message="Fetch has moved trunk (revision $target), please rebase before dcommit..."
		echo "$message"
		notify-send "SVN - $1" "$message" -t 0 -i ~/bin/bash/svn-square.jpg
		zenity --notification  --window-icon="info" zenity --notification --window-icon="info" --text="$message" &
	else
		message="Fetch has moved trunk (revision $target):"
		echo "$message"
		notify-send -t 30 "SVN - $1" "$message" -i ~/bin/bash/svn-square.jpg
	fi
else
	echo "Nothing to do."
fi
echo "-------------------"
cd - > /dev/null

