#!/bin/bash

echo $(date +"%Y-%m-%d %H:%M:%S")
cd "$2" > /dev/null
result=$(git svn fetch | tee -a /dev/stdout | wc -l)
if [ $result -gt 0 ]; then
	forward=$(git log --oneline remotes/trunk..master | wc -l)
	target=$(git svn find-rev remotes/trunk)
	if [ $forward -gt 0 ]; then
		message="Fetch has moved trunk (revision $target), please rebase before dcommit..."
		echo "$message"
		notify-send "SVN - $1" "$message" -t 0 -i ~/bin/bash/svn-square.jpg
		zenity --notification  --window-icon="info" zenity --notification --window-icon="info" --text="$message" &
	else
		message="Fetch has moved trunk (revision $target):"
		echo "$message"
		notify-send -t 30 "SVN - $1" "$message" -i ~/bin/bash/svn-square.jpg
	fi
else
	echo "Nothing to do."
fi
echo "-------------------"
cd - > /dev/null

