name: "tests"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  packaging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - run: nix-build nix/release.nix

  lint-shell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - run: nix-shell --command tests/lint-shell.sh

  lint-nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - run: nix-shell --command tests/lint-nix.sh

  spell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - run: nix-shell --command tests/spell.sh
